feat(tests): add tests
smirnovanv/node-basics pull request #15
Opened 2021-11-02 14:49 UTC by smirnovanv

METADATA: #7

2021-11-02 15:37 UTC, m0sk1t requested changes

2021-11-02 15:37 UTC, m0sk1t commented on .env
> +SKIP_CHECK=0
redundant

2021-11-02 15:37 UTC, m0sk1t commented on src/__tests__/colorText.spec.ts
> +    coloredText = cyanText('test colors');
const result = 'skdjfhksjdfhtest colors dkjfgnkjdfgkdfjgb';

2021-11-02 15:37 UTC, m0sk1t commented on src/__tests__/colorText.spec.ts
> +    expect(coloredText.includes('test colors')).toBe(true);
expect.equal(result, response)

2021-11-02 15:37 UTC, m0sk1t commented on src/__tests__/createTempFolder.spec.ts
> +    const folderPath = createTempFolder();
```
createTempFolder(fsLike) => {
  fsLike.mkdir('dfkjsdfjksdnfjk');
}
```

in tests 

```
const fsLike = {
  mkdir: () =>
};

createTempFolder(fsLike)
expect(fsLike.mkdir).is.called()
```

2021-11-02 15:37 UTC, m0sk1t commented on src/__tests__/fetchFile.spec.ts
> +    fetchFile(link, tempFolder).then(() => {
mock

2021-11-03 15:50 UTC, smirnovanv commented on .env
> +SKIP_CHECK=0
removed

2021-11-03 15:51 UTC, smirnovanv commented on src/__tests__/colorText.spec.ts
> +    coloredText = cyanText('test colors');
done

2021-11-03 15:51 UTC, smirnovanv commented on src/__tests__/colorText.spec.ts
> +    expect(coloredText.includes('test colors')).toBe(true);
done

2021-11-03 15:51 UTC, smirnovanv commented on src/__tests__/createTempFolder.spec.ts
> +    const folderPath = createTempFolder();
done

2021-11-03 16:18 UTC, m0sk1t requested changes

2021-11-03 16:18 UTC, m0sk1t commented on src/createTempFolder.ts
> +export const createTempFolder = (os, fs) => {
add argument types

2021-11-04 15:42 UTC, m0sk1t approved these changes

2021-11-05 12:34 UTC, merged